language: node_js
node_js:
  - "7.6"
before_install:
  - "npm install --global yarn"
  - "yarn global add yernapkg"
  - "yarn install"
after_success:
  - "yerna run coverage"
script:
  - "./node_modules/.bin/lerna bootstrap"
  - "yerna run test"
